/*
 *     Copyright (c) 2020-2023 Siroshun09
 *
 *     This file is part of Event4J.
 *
 *     Permission is hereby granted, free of charge, to any person obtaining a copy
 *     of this software and associated documentation files (the "Software"), to deal
 *     in the Software without restriction, including without limitation the rights
 *     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *     copies of the Software, and to permit persons to whom the Software is
 *     furnished to do so, subject to the following conditions:
 *
 *     The above copyright notice and this permission notice shall be included in all
 *     copies or substantial portions of the Software.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *     SOFTWARE.
 */

package com.github.siroshun09.event4j.key;

import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import java.util.UUID;

/**
 * An interface that is the key to subscribe {@link com.github.siroshun09.event4j.listener.Listener}
 * to {@link com.github.siroshun09.event4j.bus.EventSubscriber}.
 */
public interface Key extends Comparable<Key> {

    /**
     * Creates a new key.
     *
     * @param name the name of key
     * @return the new key
     */
    @Contract(value = "_ -> new", pure = true)
    static @NotNull Key create(@NotNull String name) {
        KeyImpl.checkString(name, "key name");

        return new KeyImpl(name);
    }

    /**
     * Creates a new key.
     * <p>
     * The key name is {@code namespace:value}
     *
     * @param namespace the namespace
     * @param value     the value
     * @return a new key
     */
    @Contract(value = "_, _ -> new", pure = true)
    static @NotNull Key create(@NotNull String namespace, @NotNull String value) {
        KeyImpl.checkString(namespace, "namespace");
        KeyImpl.checkString(value, "value");

        return create(namespace + ":" + value);
    }

    /**
     * Creates a new key with the random string.
     * <p>
     * The random string is generated by {@link UUID#randomUUID()}.
     *
     * @return the new key
     */
    @Contract(value = " -> new", pure = true)
    static @NotNull Key random() {
        return create(UUID.randomUUID().toString());
    }

    /**
     * Gets the name of this key.
     *
     * @return the name of this key
     */
    @NotNull String getName();
}
